version: '2'

services:
  web:
    build: .
    volumes:
      - ./:/app
      - ./node_modules:/app/node_modules
    ports:
      - '3000:3000'
    links:
      - mongo

  mongo:
    image: mongo:3.0
    ports:
      - '27017:27017'
    volumes:
      - /data/db
